export const ERROR_CODES = {
  FLASHCARD_NOT_FOUND: "FLASHCARD_NOT_FOUND",
  INVALID_CATEGORY: "INVALID_CATEGORY",
  QUESTION_REQUIRED: "QUESTION_REQUIRED",
  ANSWER_REQUIRED: "ANSWER_REQUIRED",
  INVALID_ID: "INVALID_ID",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
